/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 21-Mar-2021 12:36:17 AM 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Address" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Contact" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Customer" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Employee" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Hotel" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Payment" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Position" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Reservation" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Review" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Room" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Roomtype" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Service" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Service_hotel" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Service_roomtype" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

/* Create Tables */

CREATE TABLE  "Address"
(
	"Apt" NUMBER(8) NOT NULL,
	"City" VARCHAR(20) NOT NULL,
	"Country" VARCHAR(20) NOT NULL,
	"Region" VARCHAR(20) NOT NULL,
	"Street" VARCHAR(20) NOT NULL,
	"Zip" NUMBER(8) NOT NULL,
	"AddressID" NUMBER(8) NOT NULL
)
;

CREATE TABLE  "Contact"
(
	"Fax" VARCHAR(30) NULL,
	"Mail" VARCHAR(30) NOT NULL,
	"Name" VARCHAR(30) NOT NULL,
	"Phone" NUMBER(30) NOT NULL,
	"Surname" VARCHAR(30) NOT NULL,
	"ContactID" NUMBER(8) NOT NULL
)
;

CREATE TABLE  "Customer"
(
	"Alias" VARCHAR(30) NOT NULL,
	"Gender" NUMBER(1) NOT NULL,
	"Password" VARCHAR(30) NOT NULL,
	"Registrationdate" DATE NOT NULL,
	"CustomerID" NUMBER(8) NOT NULL,
	"ContactID" NUMBER(8) NOT NULL
)
;

CREATE TABLE  "Employee"
(
	"Onboard" DATE NOT NULL,
	"Resignation" DATE NULL,
	"Salary" NUMBER(8) NULL,
	"EmployeeID" NUMBER(8) NOT NULL,
	"ContactID" NUMBER(8) NOT NULL,
	"HotelID" NUMBER(8) NOT NULL,
	"PositionID" NUMBER(8) NOT NULL
)
;

CREATE TABLE  "Hotel"
(
	"Description" VARCHAR(256) NOT NULL,
	"Name" VARCHAR(30) NOT NULL,
	"Preview" BLOB NULL,
	"HotelID" NUMBER(8) NOT NULL,
	"AddressID" NUMBER(8) NOT NULL
)
;

CREATE TABLE  "Payment"
(
	"Type" NUMBER(1) NOT NULL,
	"PaymentID" NUMBER(8) NOT NULL
)
;

CREATE TABLE  "Position"
(
	"Type" VARCHAR(20) NOT NULL,
	"PositionID" NUMBER(8) NOT NULL
)
;

CREATE TABLE  "Reservation"
(
	"Enddate" DATE NOT NULL,
	"Numberofguests" NUMBER(8) NOT NULL,
	"Price" NUMBER(8) NOT NULL,
	"Startdate" DATE NOT NULL,
	"Status" NUMBER(1) NOT NULL,
	"ReservationID" NUMBER(8) NOT NULL,
	"CustomerID" NUMBER(8) NOT NULL,
	"PaymentID" NUMBER(8) NOT NULL,
	"RoomID" NUMBER(8) NOT NULL
)
;

CREATE TABLE  "Review"
(
	"Date" DATE NOT NULL,
	"Photo" BLOB NULL,
	"Stars" NUMBER(1) NOT NULL,
	"Text" VARCHAR(256) NOT NULL,
	"ReviewID" NUMBER(8) NOT NULL,
	"CustomerID" NUMBER(8) NOT NULL
)
;

CREATE TABLE  "Room"
(
	"Floor" NUMBER(8) NOT NULL,
	"RoomID" NUMBER(8) NOT NULL,
	"HotelID" NUMBER(8) NOT NULL,
	"RoomtypeID" NUMBER(8) NOT NULL
)
;

CREATE TABLE  "Roomtype"
(
	"Capacity" NUMBER(8) NOT NULL,
	"Description" VARCHAR(256) NOT NULL,
	"Price" NUMBER(8) NOT NULL,
	"RoomtypeID" NUMBER(8) NOT NULL
)
;

CREATE TABLE  "Service"
(
	"Name" VARCHAR(20) NOT NULL,
	"ServiceID" NUMBER(8) NOT NULL
)
;

CREATE TABLE  "Service_hotel"
(
	"Amount" NUMBER(8) NOT NULL,
	"Price" NUMBER(8) NOT NULL,
	"ServiceID" NUMBER(8) NOT NULL,
	"HotelID" NUMBER(8) NOT NULL,
	"Service_hotelID" varchar(1) NOT NULL
)
;

CREATE TABLE  "Service_roomtype"
(
	"Amount" NUMBER(8) NOT NULL,
	"Price" NUMBER(8) NOT NULL,
	"ServiceID" NUMBER(8) NOT NULL,
	"RoomtypeID" NUMBER(8) NOT NULL,
	"Service_roomtypeID" NUMBER(8) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks, Triggers */

ALTER TABLE  "Address" 
 ADD CONSTRAINT "PK_Address"
	PRIMARY KEY ("AddressID") 
 USING INDEX
;

ALTER TABLE  "Contact" 
 ADD CONSTRAINT "PK_Contact"
	PRIMARY KEY ("ContactID") 
 USING INDEX
;

ALTER TABLE  "Customer" 
 ADD CONSTRAINT "PK_Customer"
	PRIMARY KEY ("CustomerID") 
 USING INDEX
;

ALTER TABLE  "Employee" 
 ADD CONSTRAINT "PK_Employee"
	PRIMARY KEY ("EmployeeID") 
 USING INDEX
;

ALTER TABLE  "Hotel" 
 ADD CONSTRAINT "PK_Hotel"
	PRIMARY KEY ("HotelID") 
 USING INDEX
;

ALTER TABLE  "Payment" 
 ADD CONSTRAINT "PK_Payment"
	PRIMARY KEY ("PaymentID") 
 USING INDEX
;

ALTER TABLE  "Position" 
 ADD CONSTRAINT "PK_Position"
	PRIMARY KEY ("PositionID") 
 USING INDEX
;

ALTER TABLE  "Reservation" 
 ADD CONSTRAINT "PK_Reservation"
	PRIMARY KEY ("ReservationID") 
 USING INDEX
;

ALTER TABLE  "Review" 
 ADD CONSTRAINT "PK_Review"
	PRIMARY KEY ("ReviewID") 
 USING INDEX
;

ALTER TABLE  "Room" 
 ADD CONSTRAINT "PK_Room"
	PRIMARY KEY ("RoomID") 
 USING INDEX
;

ALTER TABLE  "Roomtype" 
 ADD CONSTRAINT "PK_Roomtype"
	PRIMARY KEY ("RoomtypeID") 
 USING INDEX
;

ALTER TABLE  "Service" 
 ADD CONSTRAINT "PK_Service"
	PRIMARY KEY ("ServiceID") 
 USING INDEX
;

ALTER TABLE  "Service_hotel" 
 ADD CONSTRAINT "PK_Service_hotel"
	PRIMARY KEY ("Service_hotelID") 
 USING INDEX
;

ALTER TABLE  "Service_roomtype" 
 ADD CONSTRAINT "PK_Service_roomtype"
	PRIMARY KEY ("Service_roomtypeID") 
 USING INDEX
;

/* Create Foreign Key Constraints */

ALTER TABLE  "Customer" 
 ADD CONSTRAINT "FK_Customer_Contact"
	FOREIGN KEY ("ContactID") REFERENCES  "Contact" ("ContactID")
;

ALTER TABLE  "Employee" 
 ADD CONSTRAINT "FK_Employee_Contact"
	FOREIGN KEY ("ContactID") REFERENCES  "Contact" ("ContactID")
;

ALTER TABLE  "Employee" 
 ADD CONSTRAINT "FK_Employee_Hotel"
	FOREIGN KEY ("HotelID") REFERENCES  "Hotel" ("HotelID")
;

ALTER TABLE  "Employee" 
 ADD CONSTRAINT "FK_Employee_Position"
	FOREIGN KEY ("PositionID") REFERENCES  "Position" ("PositionID")
;

ALTER TABLE  "Hotel" 
 ADD CONSTRAINT "FK_Hotel_Address"
	FOREIGN KEY ("AddressID") REFERENCES  "Address" ("AddressID")
;

ALTER TABLE  "Reservation" 
 ADD CONSTRAINT "FK_Reservation_Customer"
	FOREIGN KEY ("CustomerID") REFERENCES  "Customer" ("CustomerID")
;

ALTER TABLE  "Reservation" 
 ADD CONSTRAINT "FK_Reservation_Payment"
	FOREIGN KEY ("PaymentID") REFERENCES  "Payment" ("PaymentID")
;

ALTER TABLE  "Reservation" 
 ADD CONSTRAINT "FK_Reservation_Room"
	FOREIGN KEY ("RoomID") REFERENCES  "Room" ("RoomID")
;

ALTER TABLE  "Review" 
 ADD CONSTRAINT "FK_Review_Customer"
	FOREIGN KEY ("CustomerID") REFERENCES  "Customer" ("CustomerID")
;

ALTER TABLE  "Room" 
 ADD CONSTRAINT "FK_Room_Hotel"
	FOREIGN KEY ("HotelID") REFERENCES  "Hotel" ("HotelID")
;

ALTER TABLE  "Room" 
 ADD CONSTRAINT "FK_Room_Roomtype"
	FOREIGN KEY ("RoomtypeID") REFERENCES  "Roomtype" ("RoomtypeID")
;

ALTER TABLE  "Service_hotel" 
 ADD CONSTRAINT "FK_Service_Hotel_Service"
	FOREIGN KEY ("ServiceID") REFERENCES  "Service" ("ServiceID")
;

ALTER TABLE  "Service_hotel" 
 ADD CONSTRAINT "FK_Service_Hotel_Hotel"
	FOREIGN KEY ("HotelID") REFERENCES  "Hotel" ("HotelID")
;

ALTER TABLE  "Service_roomtype" 
 ADD CONSTRAINT "FK_Service_RoomType_Service"
	FOREIGN KEY ("ServiceID") REFERENCES  "Service" ("ServiceID")
;

ALTER TABLE  "Service_roomtype" 
 ADD CONSTRAINT "FK_Service_RoomType_RoomType"
	FOREIGN KEY ("RoomtypeID") REFERENCES  "Roomtype" ("RoomtypeID")
;
